[package]
name = "nemor-damos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nemor-damon = { path = "../damon" }
policy-engine = { package = "nemor-policy-engine", path = "../policy-engine" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
