[package]
name = "nemor-policy-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
actuator = { package = "nemor-actuator", path = "../actuator" }
classifier = { package = "nemor-classifier", path = "../classifier" }
common = { package = "nemor-common", path = "../common" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
