[package]
name = "nemor-zram"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
common = { package = "nemor-common", path = "../common" }
policy-engine = { package = "nemor-policy-engine", path = "../policy-engine" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
