[package]
name = "nemor-actuator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
classifier = { package = "nemor-classifier", path = "../classifier" }
collector = { package = "nemor-collector", path = "../collector" }
common = { package = "nemor-common", path = "../common" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
